### ISSUE TITLE
[DEFECT] CAPEX defined by function 

### ISSUE THREAD

**Issue by mgarrouste** [idaholab/HERON#173]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
HERON should run without error when the CAPEX of a component is defined through a function

##### What did you see instead?
```
$ heron heron_input_issue.xml
Starting HERON ...
 ... RAVEN located at "C:\Users\garrm\projects\raven"
 ... Activating CONDA environment ...
CONDA
raven_libraries          C:\Users\garrm\Miniconda3\envs\raven_libraries
Running HERON ...
Loading plugin "ExamplePlugin" at C:\Users\garrm\projects\raven\plugins\ExamplePlugin
 ... successfully imported "ExamplePlugin" ...
Loading plugin "HERON" at C:\Users\garrm\projects\raven\plugins\HERON
 ... successfully imported "HERON" ...
Loading plugin "TEAL" at C:\Users\garrm\projects\raven\plugins\TEAL
 ... successfully imported "TEAL" ...
Loading plugin "FARM" at C:\Users\garrm\projects\raven\plugins\FARM
 ... successfully imported "FARM" ...
Loading plugin "HERON_dev" at C:\Users\garrm\projects\raven\plugins\HERON_dev
 ... successfully imported "HERON_dev" ...
(            ) UTILS                    : Message         -> importing module C:\Users\garrm\projects\FORCE\use_cases\2022_05\run\functions
(    0.37 sec) <ValuedParams.Activity.Ac: Message         -> Tracking variable not specified; using "production" ...
(    0.37 sec) <HERON ARMA>      : Message -> Checking ROM at "C:\Users\garrm\projects\raven\plugins\HERON\tests\integration_tests\ARMA\Sine\arma.pk"
(    2.04 sec) <HERON ARMA>      : Message -> For DataGenerator <ARMA> "Price", detected:  interpolated,  clustered.
Traceback (most recent call last):
  File "C:/Users/garrm/projects/raven/plugins/HERON/src/main.py", line 100, in <module>
    sim.create_raven_workflow()
  File "C:/Users/garrm/projects/raven/plugins/HERON/src/main.py", line 90, in create_raven_workflow
    case.write_workflows(self._components, self._sources, self._input_dir)
  File "C:\Users\garrm\projects\raven\plugins\HERON\src\Cases.py", line 756, in write_workflows
    inner, outer, cash = template_class.createWorkflow(self, components, sources)
  File "C:\Users\garrm\projects\raven\plugins\HERON\templates\template_driver.py", line 141, in createWorkflow
    cash = self._modify_cash(cash, case, components, sources)
  File "C:\Users\garrm\projects\raven\plugins\HERON\templates\template_driver.py", line 996, in _modify_cash
    self._modify_cash_components(template, case, components)
  File "C:\Users\garrm\projects\raven\plugins\HERON\templates\template_driver.py", line 1054, in _modify_cash_components
    cfNode.append(xmlUtils.newNode('alpha',text = subCash._alpha.get_value()))
  File "C:\Users\garrm\projects\raven\plugins\HERON\src\ValuedParamHandler.py", line 144, in get_value
    return self._vp.get_value(**kwargs)
AttributeError: 'Function' object has no attribute 'get_value'
 ... Errors were encountered while running HERON.
(base)
```

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. Run the heron input file attached with the functions python script attached copied in the parent folder
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[capex_function_issue.zip](https://github.com/idaholab/HERON/files/8818781/capex_function_issue.zip)

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
It looks like in `template_driver.py` we assume if a CashFlow is `one-time` that things like `alpha`, `reference` and `scaling_factor` are Parametric ValuedParams. Thus we fail if we try to pass a Function VP into anything other than driver for one-time Cashflows. 

https://github.com/idaholab/HERON/blob/ef50f281be906eea6aa117966f8a135c3106bcc7/templates/template_driver.py#L1047-L1059

@PaulTalbot-INL What's your suggested fix for this? I can understand the assumption that a one-time CF would not require a Function VP for any of its' inputs.

I think either:

a) This restriction cannot be implicit and should error out with a better message. The documentation should be changed to reflect this as well. 

or 

b) Find a way to allow the user to specify the Function VP wherever it is accepted.

**Comment by PaulTalbot-INL** [comment]
I agree with your assessment, @dylanjm . Any of the values in a one-time (e.g. capex) CashFlow should not be dependent on activity-based information, such as Function or Activity. I think we have some subsets of acceptable input types; however the one-time and hourly repeating cashflows probably share the same input specs.

Is there a place down the line (such as when generating the HERON.Economics.CashFlow) where we can sanity check the ValuedParams used based on what period is being used for the CashFlows?

I think the philosophically correct thing to do would be to change the CashFlow node to be ether OneTime, Yearly, or Repeating and then modify the acceptable specs, but this would be a rather large impact on the input file structure.

**Comment by dylanjm** [comment]
@PaulTalbot-INL Great, I can take a look deeper into this when I have a free moment. I've pushed a quick fix in #174 that allows users to specify Function VP in one-time. That can be disregarded now. 

Also @mgarrouste and I found a small work around as well where we specify a function in `<driver>` that actually computes the `<reference_price>`. Because users are allowed to input Function VPs in the driver for One-Time Cashflows. 

@mgarrouste You can use my branch from PR #174 if you want to run your current case that way.

**Comment by PaulTalbot-INL** [comment]
It might be good to document this here, @mgarrouste why do you want to use a Function to specify the capex for a one-time cashflow?

**Comment by mgarrouste** [comment]
@PaulTalbot-INL I am modeling an HTSE plant and in the report I am using for costs the CAPEX is expressed as a function of the plant capacity

**Comment by dylanjm** [comment]
@mgarrouste If I remember right, CAPEX is expressed as a non-linear function. So it must be implemented by an external Function source instead of using the `<linear>` node.
