### ISSUE TITLE
[DEFECT] Workshop ARMA needs to be retrained.

### ISSUE THREAD

**Issue by dylanjm** [idaholab/HERON#206]
--------
Defect Description
--------

Due to some recent changes to the ARMA, we need to retrain the ARMA pk file in the workshop. 
```
Traceback (most recent call last):
  File "/Users/mcdodj/Documents/projects/HERON/src/main.py", line 119, in <module>
    sim.read_input(args.xml_input_file) # TODO expand to use arguments?
  File "/Users/mcdodj/Documents/projects/HERON/src/main.py", line 53, in read_input
    objects = input_loader.parse(inp, location, self.messageHandler)
  File "/Users/mcdodj/Documents/projects/HERON/src/../../HERON/src/input_loader.py", line 104, in parse
    case.initialize(components, sources)
  File "/Users/mcdodj/Documents/projects/HERON/src/../../HERON/src/Cases.py", line 668, in initialize
    src.checkValid(self, components, sources)
  File "/Users/mcdodj/Documents/projects/HERON/src/../../HERON/src/Placeholders.py", line 199, in checkValid
    structure = hutils.get_synthhist_structure(self._target_file)
  File "/Users/mcdodj/Documents/projects/HERON/src/../../HERON/src/_utils.py", line 124, in get_synthhist_structure
    meta = rom.writeXML().getRoot()
  File "/Users/mcdodj/Documents/projects/raven/ravenframework/Models/ROM.py", line 599, in writeXML
    engines[0].writeXML(xml)
  File "/Users/mcdodj/Documents/projects/raven/ravenframework/SupervisedLearning/ROMCollection.py", line 1604, in writeXML
    step.writeXML(newNode, targets, skip)
  File "/Users/mcdodj/Documents/projects/raven/ravenframework/SupervisedLearning/ROMCollection.py", line 977, in writeXML
    Segments.writeXML(self, writeTo, targets, skip)
  File "/Users/mcdodj/Documents/projects/raven/ravenframework/SupervisedLearning/ROMCollection.py", line 401, in writeXML
    rom.writeXML(newNode, targets, skip)
  File "/Users/mcdodj/Documents/projects/raven/ravenframework/SupervisedLearning/ARMA.py", line 1394, in writeXML
    armaNode.append(xmlUtils.newNode('std', text=arma.sigma))
  File "/usr/local/Caskroom/miniconda/base/envs/raven_libraries/lib/python3.7/site-packages/statsmodels/base/wrapper.py", line 34, in __getattribute__
    obj = getattr(results, attr)
AttributeError: 'ARMAResults' object has no attribute 'sigma'
 ... Errors were encountered while running HERON.
```

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Approved to close via #209
