### ISSUE TITLE
[DEFECT] Running debug mode with csv file

### ISSUE THREAD

**Issue by wenchichenginl** [idaholab/HERON#365]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
I would expect the run will be successful when switching from sweep mode to debug mode when the electricity price is in CSV format. 

##### What did you see instead?

The run fails.

##### Do you have a suggested fix for the development team?

N/A.

**Describe how to Reproduce**
1.  Use CSV file for debug mode where electricity price date have more than 1 year
2.  Change from Sweep mode to debug mode and run the codes
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

There were 2 warnings during the simulation run:
(1 time) <class 'DeprecationWarning'> "variables" node inputted but has been deprecated!  Please list variables in the "inputs" and "outputs" nodes instead.
(1 time) There were 1 failed runs!  Run with verbosity = debug for more details.
--------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\CHENW\projects\raven\raven_framework.py", line 25, in <module>
    sys.exit(main(True))
  File "C:\Users\CHENW\projects\raven\ravenframework\Driver.py", line 207, in main
    raven()
  File "C:\Users\CHENW\projects\raven\ravenframework\Driver.py", line 160, in raven
    simulation.run()
  File "C:\Users\CHENW\projects\raven\ravenframework\Simulation.py", line 901, in run
    self.executeStep(stepInputDict, stepInstance)
  File "C:\Users\CHENW\projects\raven\ravenframework\Simulation.py", line 834, in executeStep
    stepInstance.takeAstep(stepInputDict)
  File "C:\Users\CHENW\projects\raven\ravenframework\Steps\Step.py", line 317, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "C:\Users\CHENW\projects\raven\ravenframework\Steps\MultiRun.py", line 269, in _localTakeAstepRun
    sampler.finalizeSampler(self.failedRuns)
  File "C:\Users\CHENW\projects\raven\ravenframework\Samplers\Sampler.py", line 1119, in finalizeSampler
    self.handleFailedRuns(failedRuns)
  File "C:\Users\CHENW\projects\raven\ravenframework\Samplers\Sampler.py", line 1141, in handleFailedRuns
    self._localHandleFailedRuns(failedRuns)
  File "C:\Users\CHENW\projects\raven\ravenframework\Samplers\Sampler.py", line 1153, in _localHandleFailedRuns
    self.raiseAnError(IOError, 'There were failed runs; aborting RAVEN.')
  File "C:\Users\CHENW\projects\raven\ravenframework\BaseClasses\MessageUser.py", line 77, in raiseAnError
    self.messageHandler.error(self, etype, msg, str(tag), verbosity, color)
  File "C:\Users\CHENW\projects\raven\ravenframework\MessageHandler.py", line 235, in error
    raise etype(message)
OSError: There were failed runs; aborting RAVEN.

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Enterprise 
 - Version: [e.g. 22] 64-bit operating system, x64-based processor
 - Dependencies Installation: [CONDA or PIP] CONDA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
@wenchichenginl Please upload your reproducible example along with the failing out~inner file.
